### ISSUE TITLE
Patterns with flags are broken (again)

### ISSUE THREAD

**Issue by oxc** [h0tk3y/better-parse#12]
With the changes introduced in 0.3.3 (and 0.3.4), patterns created with flags are broken again (similar to #7), because they are combined using their serialized form.

Example:
```kotlin
private val newCommentLine by token("^\\s*--".toRegex(RegexOption.MULTILINE), ignore = true)
```

If patterns are transported using a serialized form, that string form must contain their flags, e.g.:
```regex
(?m:^\s*--)
```

Otherwise, as I said in #7, the Token factories taking a pattern should better be removed altogether.

If you decide to further support Tokens with Patterns, could you please add a test for patterns that have flags like MULTILINE or such, to prevent such breakage in the future?

**Comment by h0tk3y** [comment]
@oxc Thank you for reporting the regression! Fixed in 0.3.5 (this is basically the only change for 0.3.5).
