### ISSUE TITLE
Publish better-parse to Maven Central

### ISSUE THREAD

**Issue by bdemers** [h0tk3y/better-parse#21]
See: https://central.sonatype.org/pages/ossrh-guide.html

This will also require signing releases 😃

**Comment by h0tk3y** [comment]
@bdemers Thanks! I'll definitely consider this, especially since Bintray rejects packages with non-JAR artifacts (such as the `*.klib`s of the Kotlin/Native targets) from being synced to JCenter.

**Comment by sureshg** [comment]
@h0tk3y any plans to publish this awesome lib to maven central sooner?

**Comment by h0tk3y** [comment]
Done. The setup is complete with this commit: https://github.com/h0tk3y/better-parse/commit/7bc9bcc1cbc0474243b9dd7cafec496cf296c733. The 0.4.1 release is now available on Maven Central: https://repo1.maven.org/maven2/com/github/h0tk3y/betterParse/
