### ISSUE TITLE
Broken multiplatform deploy on 0.4.0-alpha-3

### ISSUE THREAD

**Issue by altavir** [h0tk3y/better-parse#27]
Currently, the multiplatform artifact is not resolved from common. Probably something went wrong with the deploy, or older gradle metadata is not resolved from gradle 6+. The workaround is to declare platform-specific dependencies including the metadata artifact:

```kotlin
    commonMain {
        dependencies {
            implementation("com.github.h0tk3y.betterParse:better-parse-multiplatform:0.4.0-alpha-3")
            implementation("com.github.h0tk3y.betterParse:better-parse-multiplatform-metadata:0.4.0-alpha-3")
        }
    }
    jvmMain{
        dependencies{
            implementation("com.github.h0tk3y.betterParse:better-parse-jvm:0.4.0-alpha-3")
        }
    }
    jsMain{
        dependencies{
            implementation("com.github.h0tk3y.betterParse:better-parse-js:0.4.0-alpha-3")
        }
    }
```

**Comment by h0tk3y** [comment]
Should be fixed now with the `0.4.0` release. Note: the `0.4.0` release won't work for Kotlin 1.4-M2 in multiplatform projects, please use the separate `0.4.0-1.4-M2` version.
