### ISSUE TITLE
Support kotlin 1.4.0

### ISSUE THREAD

**Issue by oxc** [h0tk3y/better-parse#30]
Could you provide a version that compiles against kotlin 1.4.0 release? The 1.4-M2 version is rejected by the compiler as "compiled by a pre-release version".
Thanks!

**Comment by oxc** [comment]
Unfortunately the demo code is no longer fully compatible between 1.3.72 and 1.4.0, because compileKotlinTaskHolder was renamed to compileKotlinTaskProvider.

**Comment by CommanderTvis** [comment]
Same issue

**Comment by ArcheCraft** [comment]
Yeah.. probably what would help ist to download the sources and just compile it yourself with Kotlin 1.4

**Comment by h0tk3y** [comment]
Closing this as obsolete. The latest release is built by Kotlin 1.4.31.
