### ISSUE TITLE
Make it buildable in jitpack

### ISSUE THREAD

**Issue by seniorjoinu** [h0tk3y/better-parse#32]
Because better-parse doesn't built well by jitpack, I'm forced to use the bintray's version. For that I need to always add additional repository declaration in gradle config. Because I'm building a library depending on better-parse, all my users are ALSO have to add additional repository in their configs. 
This is awkward.

Парни, пожалуйста.

**Comment by h0tk3y** [comment]
The latest releases are available on `MavenCentral`. I'm not sure jitpack.io compatibility is necessary now, so I'll close this issue for now. If you have other concerns, please feel free to comment on this issue.
