### ISSUE TITLE
Publish an IR compiled JS target of better-parse

### ISSUE THREAD

**Issue by CommanderTvis** [h0tk3y/better-parse#38]

**Comment by CommanderTvis** [comment]
@h0tk3y Any progress on this?

**Comment by AlexITC** [comment]
My team is interested in this too.

**Comment by CommanderTvis** [comment]
@AlexITC I have already made necessary adjustments to ensure compatibility with the IR; however, @h0tk3y has to publish a new version

**Comment by h0tk3y** [comment]
Sorry for the delay. I've just released a new version `0.4.2` which provides the JS IR artifacts.
