### ISSUE TITLE
Note that this library is not thread safe

### ISSUE THREAD

**Issue by ScottPeterJohnson** [h0tk3y/better-parse#39]
In grammars on the JVM, RegexTokens (at least) use stateful matchers, and therefore aren't thread-safe. It would be nice if the library either noted this, or was thread-safe (by creating a new matcher as needed- at a glance this doesn't seem to be an expensive JVM operation, I think that's the creation of the Pattern).

**Comment by h0tk3y** [comment]
Thanks for noticing this! I think using `ThreadLocal` matches would make sense and would make the JVM implementation thread-safe. I'll fix this.
