### ISSUE TITLE
when defining same token in Grammar, parsers referring the latter one can never get parsed

### ISSUE THREAD

**Issue by lolicon** [h0tk3y/better-parse#8]
sample code 
```

package cn.beriru

import com.github.h0tk3y.betterParse.combinators.map
import com.github.h0tk3y.betterParse.grammar.*
import com.github.h0tk3y.betterParse.parser.Parser

object AmbiguousToken : Grammar<String>() {
    val questionMark by token("""\?""")
    val lazy by token("""\?""")
    val term by lazy.map {
        it.text
    }
    override val rootParser: Parser<String> = term

    @JvmStatic
    fun main(args: Array<String>) {
        println(parseToEnd("?"))
    }
}
```

if I change rule term to `by questionMark`, everything will be ok,
is this behavior by design ?

**Comment by h0tk3y** [comment]
Yes, this is by design. A toke mixer tries to match the tokens in the same order as they are declared, from first to last. The README.MD says about it: 

> Note: the tokens order matters in some cases, because the tokenizer tries to match them in exactly this order. For instance, if `Token("a")` is listed before `Token("aa")`, the latter will never be matched. Be careful with keyword tokens
